import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1778951127866 implements MigrationInterface {
    name = 'Migration1778951127866'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "website_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "customerName" character varying NOT NULL, "customerPhone" character varying NOT NULL, "customerAddress" character varying NOT NULL, "orderNotes" character varying, "items" jsonb NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "paymentMethod" character varying NOT NULL DEFAULT 'cod', "status" character varying NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_37d0bca758bc0ceb6c0e3356650" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7c511c20875ed4bcda3c5076ad" ON "website_orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b84dd6791e5e9709a20ddfe0a1" ON "website_orders" ("clinicId") `);
        await queryRunner.query(`CREATE TABLE "clinic_contact_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "senderName" character varying NOT NULL, "senderEmail" character varying NOT NULL, "senderPhone" character varying, "subject" character varying, "body" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf485ca8817993c354f6bb3be8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae8c84c9216672804e1b0cc320" ON "clinic_contact_messages" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."clinics_plan_enum" AS ENUM('free', 'basic', 'pro', 'enterprise')`);
        await queryRunner.query(`CREATE TABLE "clinics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "email" character varying, "phone" character varying, "address" character varying, "city" character varying, "logo" character varying, "website" character varying, "licenseNumber" character varying, "registrationNumber" character varying, "vatNumber" character varying, "plan" "public"."clinics_plan_enum" NOT NULL DEFAULT 'free', "workingHours" jsonb, "settings" jsonb, "billingTemplate" jsonb DEFAULT '{}', "prescriptionTemplate" jsonb DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "trialEndsAt" TIMESTAMP, "subscriptionEndsAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c4933755297e407da44d46031c" UNIQUE ("slug"), CONSTRAINT "PK_5513b659e4d12b01a8ab3956abc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clinic_websites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" uuid NOT NULL, "pages" jsonb NOT NULL DEFAULT '[]', "globalSettings" jsonb NOT NULL DEFAULT '{}', "templateId" character varying, "isPublished" boolean NOT NULL DEFAULT false, "subdomain" character varying, "customDomain" character varying, "domainVerified" boolean NOT NULL DEFAULT false, "seo" jsonb DEFAULT '{}', "content" jsonb, "theme" jsonb DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2118418c1f71b32411d3064695c" UNIQUE ("clinicId"), CONSTRAINT "UQ_83138c3de95b8af93167ded323d" UNIQUE ("subdomain"), CONSTRAINT "PK_78d9e943ba8a697e62ae7560872" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2118418c1f71b32411d3064695" ON "clinic_websites" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'owner', 'dentist', 'receptionist', 'accountant', 'staff')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'staff', "phone" character varying, "avatar" character varying, "signatureUrl" character varying, "clinicId" uuid, "isActive" boolean NOT NULL DEFAULT true, "commissionRate" numeric(5,2), "baseSalary" numeric(10,2) DEFAULT '0', "refreshToken" character varying, "lastLoginAt" TIMESTAMP, "passwordResetToken" character varying, "passwordResetExpires" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."branches_status_enum" AS ENUM('active', 'inactive', 'pending_selection')`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" uuid NOT NULL, "name" character varying NOT NULL, "address" character varying, "phone" character varying, "email" character varying, "isActive" boolean NOT NULL DEFAULT true, "isLocked" boolean NOT NULL DEFAULT false, "status" "public"."branches_status_enum" NOT NULL DEFAULT 'active', "lastActivityAt" TIMESTAMP WITH TIME ZONE, "activatedAt" TIMESTAMP WITH TIME ZONE, "activationPeriodEnd" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbef005f9ce643c8e06eda0204" ON "branches" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."patients_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."patients_bloodgroup_enum" AS ENUM('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-')`);
        await queryRunner.query(`CREATE TABLE "patients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" uuid, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying, "phone" character varying, "dateOfBirth" TIMESTAMP, "ageYears" integer, "gender" "public"."patients_gender_enum", "bloodGroup" "public"."patients_bloodgroup_enum", "address" character varying, "emergencyContactName" character varying, "emergencyContactPhone" character varying, "allergies" text array NOT NULL DEFAULT '{}', "medicalConditions" text array NOT NULL DEFAULT '{}', "currentMedications" text array NOT NULL DEFAULT '{}', "dentalHistory" jsonb, "insuranceProvider" character varying, "insurancePolicyNumber" character varying, "notes" character varying, "avatar" character varying, "isActive" boolean NOT NULL DEFAULT true, "lastVisitAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89e26ac9371068071b0738117a" ON "patients" ("branchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e382e0c1d13b01e527f2563ed" ON "patients" ("clinicId", "email") `);
        await queryRunner.query(`CREATE TABLE "clinic_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "price" numeric(10,2) NOT NULL, "duration" integer NOT NULL DEFAULT '30', "commissionPercentage" numeric(5,2), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f351cd55bc942f6a5ac36abf3fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3cbeba6965a4de0bb3a25b5419" ON "clinic_services" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('scheduled', 'confirmed', 'checked_in', 'in_progress', 'completed', 'cancelled', 'no_show', 'rescheduled')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" uuid, "patientId" uuid NOT NULL, "dentistId" uuid NOT NULL, "serviceId" uuid, "type" character varying, "status" "public"."appointments_status_enum" NOT NULL DEFAULT 'scheduled', "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endsAt" TIMESTAMP WITH TIME ZONE NOT NULL, "durationMinutes" integer NOT NULL DEFAULT '30', "notes" character varying, "chiefComplaint" character varying, "diagnosis" character varying, "treatment" character varying, "vitals" jsonb, "prescriptions" jsonb, "followUpDate" TIMESTAMP, "cancelReason" character varying, "reminderSentAt" TIMESTAMP WITH TIME ZONE, "doctorReminderSentAt" TIMESTAMP WITH TIME ZONE, "fee" numeric(10,2), "isPaid" boolean NOT NULL DEFAULT false, "checkedInAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe0f5ef013379644038d1396cb" ON "appointments" ("dentistId", "scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_281d14b920f397a215f003d85d" ON "appointments" ("branchId", "scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b19a86e0916d25b4b8249580f1" ON "appointments" ("clinicId", "dentistId") `);
        await queryRunner.query(`CREATE INDEX "IDX_55c5a275a4b7df1bbffd742b52" ON "appointments" ("clinicId", "scheduledAt") `);
        await queryRunner.query(`CREATE TYPE "public"."waiting_queue_status_enum" AS ENUM('waiting', 'called', 'in_progress', 'done', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "waiting_queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying NOT NULL, "patientId" uuid NOT NULL, "appointmentId" uuid, "doctorId" uuid, "tokenNumber" integer NOT NULL DEFAULT '1', "status" "public"."waiting_queue_status_enum" NOT NULL DEFAULT 'waiting', "calledAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3f3a19bda8528dd04065902e095" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70dc525a71028d3da02305a9ad" ON "waiting_queue" ("clinicId", "branchId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('trial', 'active', 'past_due', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "plan" character varying NOT NULL DEFAULT 'free', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'trial', "billingCycle" character varying, "currentPeriodStart" TIMESTAMP, "currentPeriodEnd" TIMESTAMP, "cancelAt" TIMESTAMP, "features" jsonb, "externalSubscriptionId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_02beb9567811d522b1edf985043" UNIQUE ("clinicId"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_requests_type_enum" AS ENUM('activation', 'renewal', 'upgrade')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_requests_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "subscription_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "clinicId" uuid NOT NULL, "requestedPlan" character varying NOT NULL, "billingCycle" character varying, "type" "public"."subscription_requests_type_enum" NOT NULL DEFAULT 'activation', "status" "public"."subscription_requests_status_enum" NOT NULL DEFAULT 'pending', "adminNote" character varying, "contactNumber" character varying, "paymentProofUrl" character varying, "paymentMethod" character varying, "numBranches" integer, "reviewedBy" character varying, "reviewedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f97babb1f4d7eeef9d5c2937be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "name" character varying NOT NULL, "startTime" character(5) NOT NULL, "endTime" character(5) NOT NULL, "graceMinutes" integer NOT NULL DEFAULT '15', "minHoursForPresent" numeric(4,2) NOT NULL DEFAULT '4', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fca93c06d5c7af5d58ab30fb2d" ON "shifts" ("clinicId", "name") `);
        await queryRunner.query(`CREATE TABLE "shift_patterns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying, "userId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "shiftId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9889aed63041895165dc3b2abdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b5a766935552b1361c8d8ff416" ON "shift_patterns" ("clinicId", "userId", "dayOfWeek") `);
        await queryRunner.query(`CREATE TYPE "public"."shift_assignments_type_enum" AS ENUM('override', 'leave', 'off')`);
        await queryRunner.query(`CREATE TABLE "shift_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying, "userId" uuid NOT NULL, "date" date NOT NULL, "shiftId" uuid, "type" "public"."shift_assignments_type_enum" NOT NULL DEFAULT 'override', "note" character varying, "leaveId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a78d24f38deedd9fe0ea19685c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1b95a155f71b6e1887eaadb91c" ON "shift_assignments" ("clinicId", "userId", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."recalls_recalltype_enum" AS ENUM('checkup', 'followup', 'medication_review', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."recalls_status_enum" AS ENUM('pending', 'contacted', 'booked', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "recalls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "patientId" uuid NOT NULL, "createdByUserId" uuid, "dueDate" date NOT NULL, "reason" character varying, "recallType" "public"."recalls_recalltype_enum" NOT NULL DEFAULT 'checkup', "status" "public"."recalls_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "appointmentId" uuid, "reminderSentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_13ebd50c4d11c01b5d4528d5bb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb783585db7058971881aced0f" ON "recalls" ("clinicId", "patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_69f1e61cba19589d3e6e588caf" ON "recalls" ("clinicId", "status", "dueDate") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "label" character varying NOT NULL, "group" character varying NOT NULL DEFAULT 'General', "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "clinicId" uuid, "isSystem" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prescription_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "headerHtml" text, "footerHtml" text, "logoUrl" character varying, "signatureUrl" character varying, "showLogo" boolean NOT NULL DEFAULT true, "showLicenseNumber" boolean NOT NULL DEFAULT true, "showDoctorName" boolean NOT NULL DEFAULT true, "showPatientAge" boolean NOT NULL DEFAULT true, "showPatientGender" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c11f13a33b62e96eacb3e4cff80" UNIQUE ("clinicId"), CONSTRAINT "PK_81373adbc66823e27fdd89d74c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payroll_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "payrollRunId" uuid NOT NULL, "userId" uuid NOT NULL, "branchId" character varying, "baseSalary" numeric(10,2) NOT NULL DEFAULT '0', "hoursWorked" numeric(6,2) NOT NULL DEFAULT '0', "overtimeHours" numeric(6,2) NOT NULL DEFAULT '0', "overtimeRate" numeric(10,2) NOT NULL DEFAULT '0', "commissionEarned" numeric(10,2) NOT NULL DEFAULT '0', "bonus" numeric(10,2) NOT NULL DEFAULT '0', "allowances" numeric(10,2) NOT NULL DEFAULT '0', "grossPay" numeric(10,2) NOT NULL DEFAULT '0', "taxDeduction" numeric(10,2) NOT NULL DEFAULT '0', "otherDeductions" numeric(10,2) NOT NULL DEFAULT '0', "netPay" numeric(10,2) NOT NULL DEFAULT '0', "attendanceDays" integer NOT NULL DEFAULT '0', "absentDays" integer NOT NULL DEFAULT '0', "leaveDays" integer NOT NULL DEFAULT '0', "payslipUrl" character varying, "paidAt" TIMESTAMP, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ec33e61f88fae9f67704201204" UNIQUE ("payrollRunId", "userId"), CONSTRAINT "PK_749b8c91480734ee1e616d4456d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e7d9f9b2cee38c5aeba31c4750" ON "payroll_entries" ("clinicId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."payroll_runs_status_enum" AS ENUM('draft', 'finalized', 'paid')`);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "status" "public"."payroll_runs_status_enum" NOT NULL DEFAULT 'draft', "totalGross" numeric(12,2) NOT NULL DEFAULT '0', "totalDeductions" numeric(12,2) NOT NULL DEFAULT '0', "totalNet" numeric(12,2) NOT NULL DEFAULT '0', "notes" character varying, "createdBy" character varying NOT NULL, "finalizedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6890a594612fbe94cc44326fcb" ON "payroll_runs" ("clinicId", "periodStart") `);
        await queryRunner.query(`CREATE TABLE "payroll_deduction_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "lateDeductionPerHour" numeric(5,4) NOT NULL DEFAULT '1', "halfDayDeductionRate" numeric(5,4) NOT NULL DEFAULT '0.5', "absentDeductionRate" numeric(5,4) NOT NULL DEFAULT '1', "overtimeRateMultiplier" numeric(5,4) NOT NULL DEFAULT '1.5', "leaveAttendedBonusRate" numeric(5,4) NOT NULL DEFAULT '1', "standardHoursPerDay" numeric(4,2) NOT NULL DEFAULT '8', "workingDaysPerMonth" integer DEFAULT '26', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9efa87db523c02932d3daff7b62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b3bbaa3387220a893b42890608" ON "payroll_deduction_rules" ("clinicId") `);
        await queryRunner.query(`CREATE TABLE "patient_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "patientId" character varying NOT NULL, "balance" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NPR', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0a35d25c0e055931af09f86c8bd" UNIQUE ("clinicId", "patientId"), CONSTRAINT "PK_05611a4c8dfad51d74a0ef3b35a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('credit', 'debit', 'refund')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_referencetype_enum" AS ENUM('invoice', 'manual', 'refund')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "walletId" uuid NOT NULL, "patientId" character varying NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "balanceBefore" numeric(10,2) NOT NULL, "balanceAfter" numeric(10,2) NOT NULL, "description" text NOT NULL, "referenceType" "public"."wallet_transactions_referencetype_enum" NOT NULL DEFAULT 'manual', "referenceId" character varying, "createdBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_740c4a6d5ebb2e59b1892c4cbd" ON "wallet_transactions" ("clinicId", "patientId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('appointment_created', 'appointment_updated', 'appointment_cancelled', 'appointment_reminder', 'invoice_created', 'invoice_paid', 'patient_added', 'leave_requested', 'leave_approved', 'leave_rejected', 'schedule_updated', 'shift_assigned', 'holiday_created', 'notice_posted', 'notice_updated', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "userId" character varying, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "body" character varying, "link" character varying, "entityId" character varying, "branchId" character varying, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1155e69f0a41720ad1f4689ef" ON "notifications" ("clinicId", "userId", "isRead") `);
        await queryRunner.query(`CREATE TYPE "public"."notices_type_enum" AS ENUM('notice', 'holiday')`);
        await queryRunner.query(`CREATE TYPE "public"."notices_scope_enum" AS ENUM('clinic_wide', 'branch', 'team_member')`);
        await queryRunner.query(`CREATE TABLE "notices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" uuid NOT NULL, "createdByUserId" uuid, "type" "public"."notices_type_enum" NOT NULL DEFAULT 'notice', "title" character varying NOT NULL, "description" text, "startDate" date, "endDate" date, "scope" "public"."notices_scope_enum" NOT NULL DEFAULT 'clinic_wide', "targetBranchIds" jsonb DEFAULT '[]', "targetUserIds" jsonb DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3eb18c29da25d6935fcbe584237" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_12d5314747f855c118d85e744a" ON "notices" ("clinicId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_85c90a9453dc302e6b37cb96e5" ON "notices" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."leaves_leavetype_enum" AS ENUM('sick', 'casual', 'annual', 'unpaid', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."leaves_status_enum" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "leaves" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "userId" uuid NOT NULL, "leaveType" "public"."leaves_leavetype_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "reason" character varying, "status" "public"."leaves_status_enum" NOT NULL DEFAULT 'pending', "approvedByUserId" character varying, "approvalNote" character varying, "approvedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4153ec7270da3d07efd2e11e2a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90c3c4398723f750507d160799" ON "leaves" ("clinicId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."lab_works_status_enum" AS ENUM('pending', 'sent', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."lab_works_priority_enum" AS ENUM('routine', 'urgent', 'stat')`);
        await queryRunner.query(`CREATE TABLE "lab_works" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "patientId" uuid NOT NULL, "orderedById" uuid NOT NULL, "appointmentId" character varying, "labName" character varying, "testName" character varying NOT NULL, "testDescription" text, "status" "public"."lab_works_status_enum" NOT NULL DEFAULT 'pending', "priority" "public"."lab_works_priority_enum" NOT NULL DEFAULT 'routine', "clinicalNotes" text, "sampleCollectedAt" date, "resultsReceivedAt" date, "patientNotifiedAt" TIMESTAMP WITH TIME ZONE, "results" jsonb, "resultSummary" text, "attachments" jsonb, "externalRef" character varying, "cost" numeric(10,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4cf2da100952e412dbe8f46a688" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b8146d1d2fb30f46282e874df" ON "lab_works" ("clinicId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bfdc03d952daba60edb15370c" ON "lab_works" ("clinicId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_967f40817ea139e670f9e5e0d4" ON "lab_works" ("clinicId", "patientId") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'ordered', 'received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying, "supplierName" character varying, "supplierPhone" character varying, "items" jsonb NOT NULL, "totalCost" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "notes" character varying, "orderedAt" TIMESTAMP WITH TIME ZONE, "receivedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71ddcc5ac283dc75404e62ab1c" ON "purchase_orders" ("clinicId", "status") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_88481b0c4ed9ada47e9fdd67475" UNIQUE ("userId", "roleId"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" uuid NOT NULL, "name" character varying NOT NULL, "date" date NOT NULL, "endDate" date, "description" character varying, "isClinicWide" boolean NOT NULL DEFAULT true, "isTeamMemberSpecific" boolean NOT NULL DEFAULT false, "branchId" uuid, "branchIds" jsonb, "targetUserIds" jsonb DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3646bdd4c3817d954d830881dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed37eae4f5121c834d9e6d6b3d" ON "holidays" ("clinicId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae1f86fcd951e9691326d5859e" ON "holidays" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."patient_files_category_enum" AS ENUM('xray', 'report', 'document', 'image', 'other')`);
        await queryRunner.query(`CREATE TABLE "patient_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "patientId" uuid NOT NULL, "originalName" character varying NOT NULL, "storedName" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" bigint NOT NULL, "category" "public"."patient_files_category_enum" NOT NULL DEFAULT 'other', "description" character varying, "path" character varying NOT NULL, "uploadedByUserId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3bd24197d470559ed86ef22d3fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" uuid, "name" character varying NOT NULL, "description" character varying, "price" numeric(10,2) NOT NULL, "stockQuantity" integer NOT NULL DEFAULT '0', "unit" character varying, "sku" character varying, "isActive" boolean NOT NULL DEFAULT true, "reorderPoint" integer NOT NULL DEFAULT '10', "supplierName" character varying, "supplierPhone" character varying, "imageUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_53226929c629a656c1e71a8501" ON "products" ("clinicId") `);
        await queryRunner.query(`CREATE TYPE "public"."vendors_vendortype_enum" AS ENUM('supplier', 'service_provider', 'utility', 'other')`);
        await queryRunner.query(`CREATE TABLE "vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "name" character varying NOT NULL, "phone" character varying, "email" character varying, "address" character varying, "vendorType" "public"."vendors_vendortype_enum" NOT NULL DEFAULT 'other', "taxNumber" character varying, "bankAccount" character varying, "notes" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6cc173ef82f25a7cbef551cba" ON "vendors" ("clinicId", "vendorType") `);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('salaries', 'rent', 'utilities', 'medical_supplies', 'equipment', 'marketing', 'maintenance', 'software', 'lab_supplies', 'inventory', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_approvalstatus_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying, "category" "public"."expenses_category_enum" NOT NULL DEFAULT 'other', "vendorId" uuid, "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'NPR', "description" text NOT NULL, "receiptUrl" character varying, "isRecurring" boolean NOT NULL DEFAULT false, "recurringIntervalDays" integer, "referenceNumber" character varying, "expenseDate" date NOT NULL, "approvedBy" character varying, "approvalStatus" "public"."expenses_approvalstatus_enum" NOT NULL DEFAULT 'pending', "notes" character varying, "createdBy" character varying NOT NULL, "staffId" character varying, "labWorkId" character varying, "purchaseOrderId" character varying, "payrollRunId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f336d87a3a102b0bfae610af51" ON "expenses" ("clinicId", "category") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a1083deadd9211e36e8bc30b1" ON "expenses" ("clinicId", "expenseDate") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'paid', 'partially_paid', 'not_yet_paid', 'overdue', 'cancelled', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_paymentmethod_enum" AS ENUM('cash', 'esewa', 'khalti', 'paypal', 'bank_transfer', 'insurance', 'wallet_credit', 'wallet_debit')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceUuid" uuid NOT NULL DEFAULT gen_random_uuid(), "clinicId" character varying NOT NULL, "branchId" uuid, "invoiceNumber" character varying NOT NULL, "patientId" uuid NOT NULL, "appointmentId" uuid, "items" jsonb NOT NULL, "subtotal" numeric(10,2) NOT NULL DEFAULT '0', "taxPercent" numeric(5,2) NOT NULL DEFAULT '0', "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "vatPercent" numeric(5,2) NOT NULL DEFAULT '0', "vatAmount" numeric(10,2) NOT NULL DEFAULT '0', "vatNumber" character varying, "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "paidAmount" numeric(10,2) NOT NULL DEFAULT '0', "dueAmount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "paymentMethod" "public"."invoices_paymentmethod_enum", "paymentTransactionId" character varying, "paidAt" TIMESTAMP, "dueDate" TIMESTAMP, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9bebf88fb9eeaaea3e6a46795f0" UNIQUE ("invoiceUuid"), CONSTRAINT "UQ_bf8e0f9dd4558ef209ec111782d" UNIQUE ("invoiceNumber"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa113be7823bb2b7297f7e7974" ON "invoices" ("branchId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_50b03ae01dff60fe72f19c88e7" ON "invoices" ("clinicId", "status") `);
        await queryRunner.query(`CREATE TABLE "doctor_commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "doctorId" uuid NOT NULL, "invoiceId" uuid NOT NULL, "serviceId" uuid, "amount" numeric(10,2) NOT NULL, "serviceRevenue" numeric(10,2) NOT NULL, "commissionPercentage" numeric(5,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f8fda6485e7a6f1d873efa0a9dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_943f6a1f1f6b521ab6089caecd" ON "doctor_commissions" ("clinicId", "invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dbc0e6e0fc5412831f32f64fd7" ON "doctor_commissions" ("clinicId", "doctorId") `);
        await queryRunner.query(`CREATE TABLE "clinical_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "patientId" uuid NOT NULL, "doctorId" uuid NOT NULL, "appointmentId" character varying, "diagnosisNotes" text, "treatmentPlan" text, "attachments" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_88bb9264ee0dcf6cea9c92d07d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b927d4318849a577d900f450c" ON "clinical_records" ("clinicId", "patientId") `);
        await queryRunner.query(`CREATE TABLE "prescriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicalRecordId" uuid NOT NULL, "medicineName" character varying NOT NULL, "dosage" character varying, "frequency" character varying, "duration" character varying, "instructions" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_097b2cc2f2b7e56825468188503" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."downgrade_selections_status_enum" AS ENUM('pending', 'completed', 'auto')`);
        await queryRunner.query(`CREATE TABLE "downgrade_selections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" uuid NOT NULL, "newQuota" integer NOT NULL, "previousQuota" integer NOT NULL, "gracePeriodEndsAt" TIMESTAMP WITH TIME ZONE, "effectiveAt" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."downgrade_selections_status_enum" NOT NULL DEFAULT 'pending', "selectedBranchIds" jsonb, "confirmedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a15320c0fe9f8b9fe242e1db1f9" UNIQUE ("clinicId"), CONSTRAINT "PK_d417e2a137f4dedfdf66f1eb846" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe660d0c5f153215f644c564e7" ON "downgrade_selections" ("clinicId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('created', 'updated', 'deleted', 'login', 'export', 'bulk')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entitytype_enum" AS ENUM('invoice', 'patient', 'appointment', 'user', 'prescription', 'clinical_record', 'product', 'recall', 'auth', 'purchase_order', 'holiday', 'notice')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "userId" uuid, "action" "public"."audit_logs_action_enum" NOT NULL, "entityType" "public"."audit_logs_entitytype_enum" NOT NULL, "entityId" character varying, "changes" jsonb, "ipAddress" character varying, "userAgent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f93d44520fbc7e267a48d79dd5" ON "audit_logs" ("clinicId", "userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb5add00191f5790542f1d7f1d" ON "audit_logs" ("clinicId", "entityType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f51c893e688797d2695563f30" ON "audit_logs" ("clinicId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('present', 'absent', 'late', 'half_day', 'leave', 'off')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "branchId" character varying, "userId" uuid NOT NULL, "date" date NOT NULL, "shiftId" uuid, "checkIn" TIMESTAMP WITH TIME ZONE, "checkOut" TIMESTAMP WITH TIME ZONE, "hoursWorked" numeric(5,2), "lateMinutes" integer, "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'absent', "isAutoMarked" boolean NOT NULL DEFAULT false, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7613ed7287c70a7ed8ca7c192a" ON "attendance" ("clinicId", "userId", "date") `);
        await queryRunner.query(`CREATE TABLE "vitals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "patientId" uuid NOT NULL, "appointmentId" uuid, "recordedBy" uuid, "recordedAt" TIMESTAMP NOT NULL DEFAULT now(), "systolic" integer, "diastolic" integer, "pulse" integer, "temperature" numeric(4,1), "weight" numeric(5,1), "height" numeric(5,1), "spo2" integer, "bloodSugar" numeric(5,1), "notes" text, CONSTRAINT "PK_a6f02e68a2c1766b720d065dfd8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aec43d717881bb4f5cf3b0b759" ON "vitals" ("appointmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6fe81f3bcabaac4f41aadaf35" ON "vitals" ("clinicId", "patientId") `);
        await queryRunner.query(`CREATE TYPE "public"."api_keys_status_enum" AS ENUM('active', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "name" character varying NOT NULL, "keyHash" character varying NOT NULL, "keyPrefix" character varying(8) NOT NULL, "status" "public"."api_keys_status_enum" NOT NULL DEFAULT 'active', "allowedIps" character varying, "expiresAt" TIMESTAMP, "lastUsedAt" TIMESTAMP, "requestCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_df3b25181df0b4b59bd93f16e10" UNIQUE ("keyHash"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_branches" ("branch_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_79e020eef929e23dfdd6f9b8720" PRIMARY KEY ("branch_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7252d91dd610730c97d6b58ae7" ON "user_branches" ("branch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a93a8dec13e6204974dd67386e" ON "user_branches" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_d430a02aad006d8a70f3acd7d03" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`ALTER TABLE "clinic_websites" ADD CONSTRAINT "FK_2118418c1f71b32411d3064695c" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_edb259d369bd38b553cf10e04bc" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_fbef005f9ce643c8e06eda02046" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "FK_89e26ac9371068071b0738117a1" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_299d8147ef59909b1e6531e791c" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_203ee1f7e1f72db2512f1af43ab" FOREIGN KEY ("dentistId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_f77953c373efb8ab146d98e90c3" FOREIGN KEY ("serviceId") REFERENCES "clinic_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" ADD CONSTRAINT "FK_ee71e41787ee39e138a782d7677" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" ADD CONSTRAINT "FK_085a39de1edd07eefac891cdabb" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" ADD CONSTRAINT "FK_9ddfa40945c36ddf6b7540d6e40" FOREIGN KEY ("doctorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" ADD CONSTRAINT "FK_95f01a6c4ca3863921367c69062" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" ADD CONSTRAINT "FK_7f8f4ff5b8f85cda553b7dc2009" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_patterns" ADD CONSTRAINT "FK_b169f964ab65fd9ffa6cecdb281" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_patterns" ADD CONSTRAINT "FK_461beed9085ed14d8fda8a43da0" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_081820c9155a7380c6850d3d9b0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_647779813dec7e65a4f57bf878f" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recalls" ADD CONSTRAINT "FK_a9e11f8351b23b8fcf47cce2cee" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recalls" ADD CONSTRAINT "FK_75c871c01751e6964d9e2d4914a" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recalls" ADD CONSTRAINT "FK_2759a8526b7a5d9d20f145bfadf" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_ff9f023c297e77092e7526c6ae4" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_entries" ADD CONSTRAINT "FK_9760041eaaf1d953846b4cc246e" FOREIGN KEY ("payrollRunId") REFERENCES "payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_entries" ADD CONSTRAINT "FK_07584bee74c954840761e56bba7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_8a94d9d61a2b05123710b325fbf" FOREIGN KEY ("walletId") REFERENCES "patient_wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notices" ADD CONSTRAINT "FK_85c90a9453dc302e6b37cb96e50" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notices" ADD CONSTRAINT "FK_2e99f07180e824359b7f2e2db42" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_958890d2b2ef6c0e2e8cccc0743" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_works" ADD CONSTRAINT "FK_12928c16d315624cf71327484d0" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_works" ADD CONSTRAINT "FK_cede31f1b36ccbbcd479b8a308a" FOREIGN KEY ("orderedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "holidays" ADD CONSTRAINT "FK_ae1f86fcd951e9691326d5859ee" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "holidays" ADD CONSTRAINT "FK_7bcd0913f21832292fbfc2cc5fe" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_files" ADD CONSTRAINT "FK_6312a30a5e2e320febec0b46759" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_dd1b22e313f7e7d28805557261f" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_0c06976711d85f851a691e08016" FOREIGN KEY ("vendorId") REFERENCES "vendors"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1e60c34407bf8d83ae612cc079d" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_7f1f96ee217edce59c605cc9380" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_c38619b9c5659db0a6cef729b38" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" ADD CONSTRAINT "FK_21275ab36fcd4819c083ba51a34" FOREIGN KEY ("doctorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" ADD CONSTRAINT "FK_e8c6805e404e6f6bf077d1025b2" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" ADD CONSTRAINT "FK_7f3237e26658f08cadeded9732a" FOREIGN KEY ("serviceId") REFERENCES "clinic_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_records" ADD CONSTRAINT "FK_944ba522ae10d6b99ea8517c476" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_records" ADD CONSTRAINT "FK_5da7ecdb4ec42371f7815827956" FOREIGN KEY ("doctorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_e079c4079199feee79c4b0f0078" FOREIGN KEY ("clinicalRecordId") REFERENCES "clinical_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "downgrade_selections" ADD CONSTRAINT "FK_a15320c0fe9f8b9fe242e1db1f9" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_466e85b813d871bfb693f443528" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_fdf3ac61c170a1504021a534ace" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vitals" ADD CONSTRAINT "FK_18d995ee0fc66f9ebded708850c" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vitals" ADD CONSTRAINT "FK_aec43d717881bb4f5cf3b0b7595" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vitals" ADD CONSTRAINT "FK_e2f83bddfc66927b7bab851fc66" FOREIGN KEY ("recordedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_branches" ADD CONSTRAINT "FK_7252d91dd610730c97d6b58ae79" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_branches" ADD CONSTRAINT "FK_a93a8dec13e6204974dd67386ed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "user_branches" DROP CONSTRAINT "FK_a93a8dec13e6204974dd67386ed"`);
        await queryRunner.query(`ALTER TABLE "user_branches" DROP CONSTRAINT "FK_7252d91dd610730c97d6b58ae79"`);
        await queryRunner.query(`ALTER TABLE "vitals" DROP CONSTRAINT "FK_e2f83bddfc66927b7bab851fc66"`);
        await queryRunner.query(`ALTER TABLE "vitals" DROP CONSTRAINT "FK_aec43d717881bb4f5cf3b0b7595"`);
        await queryRunner.query(`ALTER TABLE "vitals" DROP CONSTRAINT "FK_18d995ee0fc66f9ebded708850c"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_fdf3ac61c170a1504021a534ace"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_466e85b813d871bfb693f443528"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "downgrade_selections" DROP CONSTRAINT "FK_a15320c0fe9f8b9fe242e1db1f9"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_e079c4079199feee79c4b0f0078"`);
        await queryRunner.query(`ALTER TABLE "clinical_records" DROP CONSTRAINT "FK_5da7ecdb4ec42371f7815827956"`);
        await queryRunner.query(`ALTER TABLE "clinical_records" DROP CONSTRAINT "FK_944ba522ae10d6b99ea8517c476"`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" DROP CONSTRAINT "FK_7f3237e26658f08cadeded9732a"`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" DROP CONSTRAINT "FK_e8c6805e404e6f6bf077d1025b2"`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" DROP CONSTRAINT "FK_21275ab36fcd4819c083ba51a34"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_c38619b9c5659db0a6cef729b38"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_7f1f96ee217edce59c605cc9380"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1e60c34407bf8d83ae612cc079d"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_0c06976711d85f851a691e08016"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_dd1b22e313f7e7d28805557261f"`);
        await queryRunner.query(`ALTER TABLE "patient_files" DROP CONSTRAINT "FK_6312a30a5e2e320febec0b46759"`);
        await queryRunner.query(`ALTER TABLE "holidays" DROP CONSTRAINT "FK_7bcd0913f21832292fbfc2cc5fe"`);
        await queryRunner.query(`ALTER TABLE "holidays" DROP CONSTRAINT "FK_ae1f86fcd951e9691326d5859ee"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "lab_works" DROP CONSTRAINT "FK_cede31f1b36ccbbcd479b8a308a"`);
        await queryRunner.query(`ALTER TABLE "lab_works" DROP CONSTRAINT "FK_12928c16d315624cf71327484d0"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_958890d2b2ef6c0e2e8cccc0743"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP CONSTRAINT "FK_2e99f07180e824359b7f2e2db42"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP CONSTRAINT "FK_85c90a9453dc302e6b37cb96e50"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_8a94d9d61a2b05123710b325fbf"`);
        await queryRunner.query(`ALTER TABLE "payroll_entries" DROP CONSTRAINT "FK_07584bee74c954840761e56bba7"`);
        await queryRunner.query(`ALTER TABLE "payroll_entries" DROP CONSTRAINT "FK_9760041eaaf1d953846b4cc246e"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_ff9f023c297e77092e7526c6ae4"`);
        await queryRunner.query(`ALTER TABLE "recalls" DROP CONSTRAINT "FK_2759a8526b7a5d9d20f145bfadf"`);
        await queryRunner.query(`ALTER TABLE "recalls" DROP CONSTRAINT "FK_75c871c01751e6964d9e2d4914a"`);
        await queryRunner.query(`ALTER TABLE "recalls" DROP CONSTRAINT "FK_a9e11f8351b23b8fcf47cce2cee"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_647779813dec7e65a4f57bf878f"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_081820c9155a7380c6850d3d9b0"`);
        await queryRunner.query(`ALTER TABLE "shift_patterns" DROP CONSTRAINT "FK_461beed9085ed14d8fda8a43da0"`);
        await queryRunner.query(`ALTER TABLE "shift_patterns" DROP CONSTRAINT "FK_b169f964ab65fd9ffa6cecdb281"`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" DROP CONSTRAINT "FK_7f8f4ff5b8f85cda553b7dc2009"`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" DROP CONSTRAINT "FK_95f01a6c4ca3863921367c69062"`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" DROP CONSTRAINT "FK_9ddfa40945c36ddf6b7540d6e40"`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" DROP CONSTRAINT "FK_085a39de1edd07eefac891cdabb"`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" DROP CONSTRAINT "FK_ee71e41787ee39e138a782d7677"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_f77953c373efb8ab146d98e90c3"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_203ee1f7e1f72db2512f1af43ab"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_299d8147ef59909b1e6531e791c"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "FK_89e26ac9371068071b0738117a1"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_fbef005f9ce643c8e06eda02046"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_edb259d369bd38b553cf10e04bc"`);
        await queryRunner.query(`ALTER TABLE "clinic_websites" DROP CONSTRAINT "FK_2118418c1f71b32411d3064695c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a93a8dec13e6204974dd67386e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7252d91dd610730c97d6b58ae7"`);
        await queryRunner.query(`DROP TABLE "user_branches"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP TYPE "public"."api_keys_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6fe81f3bcabaac4f41aadaf35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aec43d717881bb4f5cf3b0b759"`);
        await queryRunner.query(`DROP TABLE "vitals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7613ed7287c70a7ed8ca7c192a"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f51c893e688797d2695563f30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb5add00191f5790542f1d7f1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f93d44520fbc7e267a48d79dd5"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe660d0c5f153215f644c564e7"`);
        await queryRunner.query(`DROP TABLE "downgrade_selections"`);
        await queryRunner.query(`DROP TYPE "public"."downgrade_selections_status_enum"`);
        await queryRunner.query(`DROP TABLE "prescriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b927d4318849a577d900f450c"`);
        await queryRunner.query(`DROP TABLE "clinical_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbc0e6e0fc5412831f32f64fd7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_943f6a1f1f6b521ab6089caecd"`);
        await queryRunner.query(`DROP TABLE "doctor_commissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50b03ae01dff60fe72f19c88e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa113be7823bb2b7297f7e7974"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a1083deadd9211e36e8bc30b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f336d87a3a102b0bfae610af51"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_approvalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6cc173ef82f25a7cbef551cba"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP TYPE "public"."vendors_vendortype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53226929c629a656c1e71a8501"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "patient_files"`);
        await queryRunner.query(`DROP TYPE "public"."patient_files_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae1f86fcd951e9691326d5859e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed37eae4f5121c834d9e6d6b3d"`);
        await queryRunner.query(`DROP TABLE "holidays"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71ddcc5ac283dc75404e62ab1c"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_967f40817ea139e670f9e5e0d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bfdc03d952daba60edb15370c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b8146d1d2fb30f46282e874df"`);
        await queryRunner.query(`DROP TABLE "lab_works"`);
        await queryRunner.query(`DROP TYPE "public"."lab_works_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lab_works_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90c3c4398723f750507d160799"`);
        await queryRunner.query(`DROP TABLE "leaves"`);
        await queryRunner.query(`DROP TYPE "public"."leaves_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leaves_leavetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85c90a9453dc302e6b37cb96e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12d5314747f855c118d85e744a"`);
        await queryRunner.query(`DROP TABLE "notices"`);
        await queryRunner.query(`DROP TYPE "public"."notices_scope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notices_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1155e69f0a41720ad1f4689ef"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_740c4a6d5ebb2e59b1892c4cbd"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_referencetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "patient_wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3bbaa3387220a893b42890608"`);
        await queryRunner.query(`DROP TABLE "payroll_deduction_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6890a594612fbe94cc44326fcb"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_runs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7d9f9b2cee38c5aeba31c4750"`);
        await queryRunner.query(`DROP TABLE "payroll_entries"`);
        await queryRunner.query(`DROP TABLE "prescription_templates"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69f1e61cba19589d3e6e588caf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb783585db7058971881aced0f"`);
        await queryRunner.query(`DROP TABLE "recalls"`);
        await queryRunner.query(`DROP TYPE "public"."recalls_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recalls_recalltype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b95a155f71b6e1887eaadb91c"`);
        await queryRunner.query(`DROP TABLE "shift_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."shift_assignments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5a766935552b1361c8d8ff416"`);
        await queryRunner.query(`DROP TABLE "shift_patterns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fca93c06d5c7af5d58ab30fb2d"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TABLE "subscription_requests"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_requests_type_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70dc525a71028d3da02305a9ad"`);
        await queryRunner.query(`DROP TABLE "waiting_queue"`);
        await queryRunner.query(`DROP TYPE "public"."waiting_queue_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55c5a275a4b7df1bbffd742b52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b19a86e0916d25b4b8249580f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_281d14b920f397a215f003d85d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0f5ef013379644038d1396cb"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cbeba6965a4de0bb3a25b5419"`);
        await queryRunner.query(`DROP TABLE "clinic_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e382e0c1d13b01e527f2563ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89e26ac9371068071b0738117a"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP TYPE "public"."patients_bloodgroup_enum"`);
        await queryRunner.query(`DROP TYPE "public"."patients_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbef005f9ce643c8e06eda0204"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TYPE "public"."branches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2118418c1f71b32411d3064695"`);
        await queryRunner.query(`DROP TABLE "clinic_websites"`);
        await queryRunner.query(`DROP TABLE "clinics"`);
        await queryRunner.query(`DROP TYPE "public"."clinics_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae8c84c9216672804e1b0cc320"`);
        await queryRunner.query(`DROP TABLE "clinic_contact_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b84dd6791e5e9709a20ddfe0a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c511c20875ed4bcda3c5076ad"`);
        await queryRunner.query(`DROP TABLE "website_orders"`);
    }

}
