import { MigrationInterface, QueryRunner } from "typeorm";
export class Migration1781849186285 implements MigrationInterface {
    name = 'Migration1781849186285'
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_edb259d369bd38b553cf10e04bc"`);
        await queryRunner.query(`CREATE TABLE "patient_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying, "email" character varying, "firstName" character varying, "lastName" character varying, "dateOfBirth" TIMESTAMP, "gender" character varying, "avatarUrl" character varying, "otpHash" character varying, "otpExpires" TIMESTAMP, "refreshToken" character varying, "notificationPreferences" jsonb, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9acdc69a7b4d35934d80e3ccb6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abcb023cf5a4219078e202411f" ON "patient_accounts" ("email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cf359f1b29378e282bdea11ca1" ON "patient_accounts" ("phone") WHERE "phone" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" uuid, "branchId" character varying, "doctorUserId" character varying, "patientAccountId" uuid NOT NULL, "appointmentId" character varying, "rating" smallint NOT NULL, "comment" text, "clinicResponse" text, "doctorResponse" text, "responseAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c72930a3ea13b68580f7a180a" ON "reviews" ("patientAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f4d44da14f1a448f3a658ede3" ON "reviews" ("doctorUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b99eea44bc9f00848d545ff92" ON "reviews" ("clinicId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_45a6cefc24d5af16842be69a65" ON "reviews" ("appointmentId") `);
        await queryRunner.query(`CREATE TYPE "public"."patient_account_links_relation_enum" AS ENUM('self', 'child', 'spouse', 'parent', 'other')`);
        await queryRunner.query(`CREATE TABLE "patient_account_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientAccountId" uuid NOT NULL, "clinicPatientId" character varying, "relation" "public"."patient_account_links_relation_enum" NOT NULL DEFAULT 'self', "label" character varying, "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fb8f6d6d68bbcae4109d03faad7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e3280101825dd626eb6967f053" ON "patient_account_links" ("patientAccountId", "clinicPatientId") `);
        await queryRunner.query(`CREATE TABLE "intake_form_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying, "doctorUserId" character varying, "name" character varying NOT NULL, "specialty" character varying, "fields" jsonb NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_229c871cbbd86c692dff2df4f99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "intake_form_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "templateId" character varying NOT NULL, "appointmentId" character varying NOT NULL, "patientAccountId" character varying NOT NULL, "responses" jsonb NOT NULL, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52b4f1d6fb6c3f80981b3a2c0f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doctor_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorUserId" uuid NOT NULL, "name" character varying NOT NULL, "address" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1231533eed08621c9e8867c5b52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."independent_availability_consultationtype_enum" AS ENUM('in_person', 'video', 'both')`);
        await queryRunner.query(`CREATE TABLE "independent_availability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorUserId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "slotDurationMinutes" integer NOT NULL DEFAULT '30', "consultationType" "public"."independent_availability_consultationtype_enum" NOT NULL DEFAULT 'both', "locationId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b0624f02542e9686949bf7394df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doctor_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "specializations" text, "qualifications" text, "yearsOfExperience" integer NOT NULL DEFAULT '0', "bio" text, "consultationFee" numeric(10,2), "videoConsultationFee" numeric(10,2), "languagesSpoken" text, "profilePhotoUrl" character varying, "address" text, "latitude" numeric(10,7), "longitude" numeric(10,7), "isPubliclyListed" boolean NOT NULL DEFAULT false, "isAvailableForInstantConsult" boolean NOT NULL DEFAULT false, "lastSeenAt" TIMESTAMP, "rating" numeric(3,2), "reviewCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a798afca9436b00dac80f911a83" UNIQUE ("userId"), CONSTRAINT "REL_a798afca9436b00dac80f911a8" UNIQUE ("userId"), CONSTRAINT "PK_b07c128005f6a0d0135d6e7353b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a798afca9436b00dac80f911a8" ON "doctor_profiles" ("userId") `);
        await queryRunner.query(`CREATE TABLE "consent_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying, "doctorUserId" character varying, "name" character varying NOT NULL, "bodyText" text NOT NULL, "requiredCheckboxes" jsonb NOT NULL, "specialty" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8dad5a4035191a16c11cdecf846" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consent_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "templateId" character varying NOT NULL, "appointmentId" character varying NOT NULL, "patientAccountId" character varying NOT NULL, "signatureBase64" text NOT NULL, "checkedBoxes" jsonb NOT NULL, "ipAddress" character varying, "signedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a1643028ebe84b2ce6bee0b7c5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."doctor_clinic_affiliations_status_enum" AS ENUM('invited', 'active', 'suspended', 'removed')`);
        await queryRunner.query(`CREATE TABLE "doctor_clinic_affiliations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorUserId" uuid NOT NULL, "clinicId" uuid NOT NULL, "branchId" uuid, "status" "public"."doctor_clinic_affiliations_status_enum" NOT NULL DEFAULT 'invited', "invitedAt" TIMESTAMP, "joinedAt" TIMESTAMP, "isPrimaryEmployment" boolean NOT NULL DEFAULT false, "commissionPercentage" numeric(5,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4bcef9e41c47190684326e26006" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80f1573c1e7464da6b3b0960c0" ON "doctor_clinic_affiliations" ("doctorUserId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5eacbaa490bf768c36adfe97b5" ON "doctor_clinic_affiliations" ("clinicId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11653c9d183b9dd964e47b6387" ON "doctor_clinic_affiliations" ("doctorUserId", "clinicId") `);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "isPubliclyListed" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "publicDescription" text`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "coverImageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "galleryImages" text`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "categoryTags" text`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "openingHours" jsonb`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "acceptsInsurance" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "insuranceProviders" text`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "languagesSpoken" text`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "isEmergencyCapable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "isOpen24Hours" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "rating" numeric(3,2)`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "reviewCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "cancellationWindowHours" integer NOT NULL DEFAULT '24'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isEmailVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailOtpHash" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailOtpExpires" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "consultationType" character varying DEFAULT 'in_person'`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "bookingContext" character varying DEFAULT 'clinic'`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "videoRoomUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "videoRoomId" character varying`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "independentLocationId" character varying`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "cancellationReason" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'owner', 'dentist', 'doctor', 'receptionist', 'accountant', 'staff')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'staff'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "halfDayDeductionRate" SET DEFAULT '0.5'`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "overtimeRateMultiplier" SET DEFAULT '1.5'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50b03ae01dff60fe72f19c88e7"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceUuid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceUuid" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "clinicId" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_50b03ae01dff60fe72f19c88e7" ON "invoices" ("clinicId", "status") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_edb259d369bd38b553cf10e04bc" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_0b99eea44bc9f00848d545ff928" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_8c72930a3ea13b68580f7a180aa" FOREIGN KEY ("patientAccountId") REFERENCES "patient_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" ADD CONSTRAINT "FK_6ed6c6d734834a0354210115303" FOREIGN KEY ("patientAccountId") REFERENCES "patient_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_locations" ADD CONSTRAINT "FK_b1933901677dd3bdf48564876fd" FOREIGN KEY ("doctorUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "independent_availability" ADD CONSTRAINT "FK_ea7ab24c0a126f207283aa2b650" FOREIGN KEY ("doctorUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "independent_availability" ADD CONSTRAINT "FK_459f585a1ef461d43609702c3cd" FOREIGN KEY ("locationId") REFERENCES "doctor_locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_profiles" ADD CONSTRAINT "FK_a798afca9436b00dac80f911a83" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" ADD CONSTRAINT "FK_74febab7a076f846bee1198ceb0" FOREIGN KEY ("doctorUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" ADD CONSTRAINT "FK_0facbbd802a7319f3e14127cf62" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" ADD CONSTRAINT "FK_eaed4b12ec44d22dbaf19ee0baf" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" DROP CONSTRAINT "FK_eaed4b12ec44d22dbaf19ee0baf"`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" DROP CONSTRAINT "FK_0facbbd802a7319f3e14127cf62"`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" DROP CONSTRAINT "FK_74febab7a076f846bee1198ceb0"`);
        await queryRunner.query(`ALTER TABLE "doctor_profiles" DROP CONSTRAINT "FK_a798afca9436b00dac80f911a83"`);
        await queryRunner.query(`ALTER TABLE "independent_availability" DROP CONSTRAINT "FK_459f585a1ef461d43609702c3cd"`);
        await queryRunner.query(`ALTER TABLE "independent_availability" DROP CONSTRAINT "FK_ea7ab24c0a126f207283aa2b650"`);
        await queryRunner.query(`ALTER TABLE "doctor_locations" DROP CONSTRAINT "FK_b1933901677dd3bdf48564876fd"`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" DROP CONSTRAINT "FK_6ed6c6d734834a0354210115303"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_8c72930a3ea13b68580f7a180aa"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_0b99eea44bc9f00848d545ff928"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_edb259d369bd38b553cf10e04bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50b03ae01dff60fe72f19c88e7"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "clinicId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceUuid" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceUuid" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`CREATE INDEX "IDX_50b03ae01dff60fe72f19c88e7" ON "invoices" ("clinicId", "status") `);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "overtimeRateMultiplier" SET DEFAULT 1.5`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "halfDayDeductionRate" SET DEFAULT 0.5`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('super_admin', 'owner', 'dentist', 'receptionist', 'accountant', 'staff')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'staff'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "cancellationReason"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "independentLocationId"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "videoRoomId"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "videoRoomUrl"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "bookingContext"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "consultationType"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailOtpExpires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailOtpHash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isEmailVerified"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "cancellationWindowHours"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "reviewCount"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "isOpen24Hours"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "isEmergencyCapable"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "languagesSpoken"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "insuranceProviders"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "acceptsInsurance"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "openingHours"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "categoryTags"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "galleryImages"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "coverImageUrl"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "publicDescription"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "isPubliclyListed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11653c9d183b9dd964e47b6387"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eacbaa490bf768c36adfe97b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80f1573c1e7464da6b3b0960c0"`);
        await queryRunner.query(`DROP TABLE "doctor_clinic_affiliations"`);
        await queryRunner.query(`DROP TYPE "public"."doctor_clinic_affiliations_status_enum"`);
        await queryRunner.query(`DROP TABLE "consent_submissions"`);
        await queryRunner.query(`DROP TABLE "consent_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a798afca9436b00dac80f911a8"`);
        await queryRunner.query(`DROP TABLE "doctor_profiles"`);
        await queryRunner.query(`DROP TABLE "independent_availability"`);
        await queryRunner.query(`DROP TYPE "public"."independent_availability_consultationtype_enum"`);
        await queryRunner.query(`DROP TABLE "doctor_locations"`);
        await queryRunner.query(`DROP TABLE "intake_form_submissions"`);
        await queryRunner.query(`DROP TABLE "intake_form_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3280101825dd626eb6967f053"`);
        await queryRunner.query(`DROP TABLE "patient_account_links"`);
        await queryRunner.query(`DROP TYPE "public"."patient_account_links_relation_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45a6cefc24d5af16842be69a65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b99eea44bc9f00848d545ff92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f4d44da14f1a448f3a658ede3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c72930a3ea13b68580f7a180a"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf359f1b29378e282bdea11ca1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abcb023cf5a4219078e202411f"`);
        await queryRunner.query(`DROP TABLE "patient_accounts"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_edb259d369bd38b553cf10e04bc" FOREIGN KEY ("clinicId") REFERENCES "clinics"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }
}
