import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1782924499469 implements MigrationInterface {
    name = 'Migration1782924499469'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sync_meta" ("key" character varying(100) NOT NULL, "value" text, CONSTRAINT "PK_187d1b3fbf4d330e1a265e77695" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TYPE "public"."sync_devices_status_enum" AS ENUM('active', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "sync_devices" ("syncStatus" character varying(20) NOT NULL DEFAULT 'synced', "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clinicId" character varying NOT NULL, "registeredByUserId" character varying NOT NULL, "deviceName" character varying NOT NULL, "tokenHash" character varying NOT NULL, "tokenPrefix" character varying(8) NOT NULL, "status" "public"."sync_devices_status_enum" NOT NULL DEFAULT 'active', "lastUsedAt" TIMESTAMP, "lastUsedIp" character varying, "revokedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6210f72cc575206f48537a609f4" UNIQUE ("tokenHash"), CONSTRAINT "PK_186168376add05650e92ebeb7b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actionType" character varying(64) NOT NULL, "payload" jsonb NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "attempts" integer NOT NULL DEFAULT '0', "lastError" text, "clinicId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_340ab539f309f03bdaa14aa7649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c0a97287efc99f7e6274658e98" ON "outbox" ("status") `);
        await queryRunner.query(`CREATE TABLE "auth_cache" ("userId" character varying(36) NOT NULL, "role" character varying(50) NOT NULL, "clinicId" character varying(36), "permissions" jsonb NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastValidatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b453ccc752b1331714fea438bb" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`ALTER TABLE "clinics" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "clinic_services" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "shift_patterns" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "prescription_templates" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "payroll_entries" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "patient_wallets" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "notices" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "lab_works" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "intake_form_templates" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "intake_form_submissions" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "holidays" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "patient_files" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "vendors" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "doctor_locations" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "independent_availability" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "doctor_profiles" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "dental_charts" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "consent_templates" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "consent_submissions" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "clinical_records" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "downgrade_selections" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "blood_tests" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "vitals" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "syncStatus" character varying(20) NOT NULL DEFAULT 'synced'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "allergies"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "allergies" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "medicalConditions"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "medicalConditions" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "currentMedications"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "currentMedications" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "status" character varying NOT NULL DEFAULT 'trial'`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_requests_type_enum"`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" ADD "type" character varying NOT NULL DEFAULT 'activation'`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD "startTime" character varying(5) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD "endTime" character varying(5) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "halfDayDeductionRate" SET DEFAULT '0.5'`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "overtimeRateMultiplier" SET DEFAULT '1.5'`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" DROP COLUMN "relation"`);
        await queryRunner.query(`DROP TYPE "public"."patient_account_links_relation_enum"`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" ADD "relation" character varying NOT NULL DEFAULT 'self'`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" DROP COLUMN "verificationStatus"`);
        await queryRunner.query(`DROP TYPE "public"."patient_account_links_verificationstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" ADD "verificationStatus" character varying NOT NULL DEFAULT 'auto_matched'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c06eafd4c0c19cdbb5021d94f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f1901a44cdc1e4c59b4c32b19"`);
        await queryRunner.query(`ALTER TABLE "refill_requests" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."refill_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "refill_requests" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23ec54dc842161ba9b9947c908"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22bf1c13419bf1e551f8e3ed53"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."referrals_status_enum"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceUuid" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_8c06eafd4c0c19cdbb5021d94f" ON "refill_requests" ("doctorId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f1901a44cdc1e4c59b4c32b19" ON "refill_requests" ("clinicId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_23ec54dc842161ba9b9947c908" ON "referrals" ("referringClinicId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_22bf1c13419bf1e551f8e3ed53" ON "referrals" ("targetClinicId", "status") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_22bf1c13419bf1e551f8e3ed53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23ec54dc842161ba9b9947c908"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f1901a44cdc1e4c59b4c32b19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c06eafd4c0c19cdbb5021d94f"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceUuid" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."referrals_status_enum" AS ENUM('pending', 'accepted', 'completed', 'declined')`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "status" "public"."referrals_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_22bf1c13419bf1e551f8e3ed53" ON "referrals" ("targetClinicId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_23ec54dc842161ba9b9947c908" ON "referrals" ("referringClinicId", "status") `);
        await queryRunner.query(`ALTER TABLE "refill_requests" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."refill_requests_status_enum" AS ENUM('pending', 'approved', 'denied')`);
        await queryRunner.query(`ALTER TABLE "refill_requests" ADD "status" "public"."refill_requests_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_6f1901a44cdc1e4c59b4c32b19" ON "refill_requests" ("clinicId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c06eafd4c0c19cdbb5021d94f" ON "refill_requests" ("doctorId", "status") `);
        await queryRunner.query(`ALTER TABLE "patient_account_links" DROP COLUMN "verificationStatus"`);
        await queryRunner.query(`CREATE TYPE "public"."patient_account_links_verificationstatus_enum" AS ENUM('auto_matched', 'pending_claim', 'verified', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" ADD "verificationStatus" "public"."patient_account_links_verificationstatus_enum" NOT NULL DEFAULT 'auto_matched'`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" DROP COLUMN "relation"`);
        await queryRunner.query(`CREATE TYPE "public"."patient_account_links_relation_enum" AS ENUM('self', 'child', 'spouse', 'parent', 'other')`);
        await queryRunner.query(`ALTER TABLE "patient_account_links" ADD "relation" "public"."patient_account_links_relation_enum" NOT NULL DEFAULT 'self'`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "overtimeRateMultiplier" SET DEFAULT 1.5`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" ALTER COLUMN "halfDayDeductionRate" SET DEFAULT 0.5`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD "endTime" character(5) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD "startTime" character(5) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_requests_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" ADD "status" "public"."subscription_requests_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_requests_type_enum" AS ENUM('activation', 'renewal', 'upgrade')`);
        await queryRunner.query(`ALTER TABLE "subscription_requests" ADD "type" "public"."subscription_requests_type_enum" NOT NULL DEFAULT 'activation'`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('trial', 'active', 'past_due', 'cancelled', 'expired')`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'trial'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "currentMedications"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "currentMedications" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "medicalConditions"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "medicalConditions" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "allergies"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "allergies" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "vitals" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "blood_tests" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "downgrade_selections" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "doctor_commissions" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "clinical_records" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "consent_submissions" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "consent_templates" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "dental_charts" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "doctor_clinic_affiliations" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "doctor_profiles" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "independent_availability" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "doctor_locations" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "vendors" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "patient_files" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "holidays" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "intake_form_submissions" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "intake_form_templates" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "lab_works" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "patient_wallets" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "payroll_deduction_rules" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "payroll_entries" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "payroll_runs" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "prescription_templates" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "shift_patterns" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "waiting_queue" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "clinic_services" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`ALTER TABLE "clinics" DROP COLUMN "syncStatus"`);
        await queryRunner.query(`DROP TABLE "auth_cache"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0a97287efc99f7e6274658e98"`);
        await queryRunner.query(`DROP TABLE "outbox"`);
        await queryRunner.query(`DROP TABLE "sync_devices"`);
        await queryRunner.query(`DROP TYPE "public"."sync_devices_status_enum"`);
        await queryRunner.query(`DROP TABLE "sync_meta"`);
    }

}
