import { Injectable } from '@nestjs/common';
import { Invoice } from '../billing/entities/invoice.entity';
import { Clinic } from '../clinics/entities/clinic.entity';
import { renderPdfDoc, fetchImageAsDataUri, PDF_COLORS } from '../common/pdf/pdf-printer.util';

@Injectable()
export class PdfService {
  // NOTE: buildInvoiceHtml() below is kept as-is and untouched — it's a
  // plain HTML template, not involved in PDF generation anymore. Rendering
  // now goes through pdfmake (see pdf-printer.util.ts) instead of
  // html-pdf-node/puppeteer, so this method no longer needs a headless
  // browser at all.
  async generateInvoicePdf(invoice: Invoice, clinic: Clinic): Promise<Buffer> {
    const fmtDate = (d: any) =>
      d ? new Date(d).toLocaleDateString('en', { year: 'numeric', month: 'long', day: 'numeric' }) : '—';
    const fmtNPR = (n: number | string) => `NPR ${Number(n).toLocaleString('en')}`;

    const tpl = clinic.billingTemplate || {};
    const themeColor = tpl.themeColor || '#027cc6';
    const showLogo = tpl.showLogo === true;
    const showVat = tpl.showVatNumber === true;
    const showReg = tpl.showRegistrationNumber === true;
    const showLicense = tpl.showLicenseNumber === true;

    const API_BASE = process.env.API_BASE_URL || 'http://localhost:4000';
    let logoDataUri: string | null = null;
    if (showLogo && clinic?.logo) {
      const logoUrl = clinic.logo.startsWith('http') ? clinic.logo : `${API_BASE}${clinic.logo}`;
      logoDataUri = await fetchImageAsDataUri(logoUrl);
    }

    const clinicMetaLines = [
      clinic?.address,
      clinic?.phone,
      clinic?.email,
      showLicense && clinic?.licenseNumber ? `License: ${clinic.licenseNumber}` : null,
      showReg && clinic?.registrationNumber ? `Reg No: ${clinic.registrationNumber}` : null,
      // Labeled "PAN/VAT No" rather than just "VAT No" — in Nepal, IRD issues
      // one and the same number for both (a business only gets a distinct
      // "VAT number" by registering its existing PAN for VAT), so a clinic
      // that has this number but ISN'T VAT-registered would be printing a
      // false "VAT No" (implying VAT registration/collection it doesn't
      // have) if labeled that way. "PAN/VAT No" is accurate either way and
      // is standard practice on Nepali bills.
      showVat && clinic?.vatNumber ? `PAN/VAT No: ${clinic.vatNumber}` : null,
    ].filter(Boolean) as string[];

    const isPaid = invoice.status === 'paid';
    const itemRows = (invoice.items || []).map((item: any) => [
      { text: item.description, margin: [0, 4, 0, 4] as [number, number, number, number] },
      { text: String(item.quantity), alignment: 'center', margin: [0, 4, 0, 4] as [number, number, number, number] },
      { text: fmtNPR(item.unitPrice), alignment: 'right', margin: [0, 4, 0, 4] as [number, number, number, number] },
      { text: fmtNPR(item.total), alignment: 'right', bold: true, margin: [0, 4, 0, 4] as [number, number, number, number] },
    ]);

    const totalsRows: any[] = [
      ['Subtotal', { text: fmtNPR(invoice.subtotal), alignment: 'right' }],
    ];
    if (Number(invoice.taxAmount) > 0) {
      totalsRows.push([`VAT (${invoice.taxPercent}%)`, { text: fmtNPR(invoice.taxAmount), alignment: 'right' }]);
    }
    if (Number(invoice.discountAmount) > 0) {
      totalsRows.push(['Discount', { text: `- ${fmtNPR(invoice.discountAmount)}`, alignment: 'right' }]);
    }
    totalsRows.push([
      { text: 'Total', bold: true, fillColor: themeColor, color: '#ffffff', margin: [4, 4, 4, 4] },
      { text: fmtNPR(invoice.total), alignment: 'right', bold: true, fillColor: themeColor, color: '#ffffff', margin: [4, 4, 4, 4] },
    ]);
    if (Number(invoice.paidAmount) > 0) {
      totalsRows.push([
        { text: 'Paid', color: PDF_COLORS.mutedText },
        { text: fmtNPR(invoice.paidAmount), alignment: 'right', color: PDF_COLORS.mutedText },
      ]);
    }
    if (Number(invoice.dueAmount) > 0) {
      totalsRows.push([
        { text: 'Balance Due', bold: true, color: '#dc2626' },
        { text: fmtNPR(invoice.dueAmount), alignment: 'right', bold: true, color: '#dc2626' },
      ]);
    }

    const footerParts = [`Generated by DentalOS • ${new Date().getFullYear()}`];
    if (showVat && clinic?.vatNumber) footerParts.push(`PAN/VAT: ${clinic.vatNumber}`);
    if (showReg && clinic?.registrationNumber) footerParts.push(`Reg: ${clinic.registrationNumber}`);

    const docDefinition: any = {
      pageSize: 'A4',
      pageMargins: [36, 36, 36, 36],
      content: [
        {
          columns: [
            {
              width: '*',
              stack: [
                { text: 'INVOICE', fontSize: 20, bold: true, color: PDF_COLORS.darkText },
                { text: `#${invoice.invoiceNumber}`, bold: true, margin: [0, 6, 0, 2] },
                { text: `Issued: ${fmtDate(invoice.createdAt)}`, color: PDF_COLORS.mutedText, fontSize: 9 },
                ...(invoice.dueDate ? [{ text: `Due: ${fmtDate(invoice.dueDate)}`, color: PDF_COLORS.mutedText, fontSize: 9 }] : []),
                {
                  table: {
                    body: [[
                      {
                        text: invoice.status.replace('_', ' ').toUpperCase(),
                        bold: true,
                        fontSize: 8,
                        color: isPaid ? '#065f46' : '#991b1b',
                        fillColor: isPaid ? '#d1fae5' : '#fee2e2',
                        margin: [6, 3, 6, 3],
                      },
                    ]],
                  },
                  layout: 'noBorders',
                  margin: [0, 8, 0, 0] as [number, number, number, number],
                },
              ],
            },
            {
              width: 220,
              stack: [
                ...(logoDataUri ? [{ image: logoDataUri, width: 100, alignment: 'right' as const, margin: [0, 0, 0, 6] as [number, number, number, number] }] : []),
                { text: clinic?.name || 'Dental Clinic', bold: true, alignment: 'right' as const },
                ...clinicMetaLines.map((line) => ({ text: line, fontSize: 8, color: PDF_COLORS.mutedText, alignment: 'right' as const })),
              ],
            },
          ],
          columnGap: 20,
        },
        { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 523, y2: 0, lineWidth: 3, lineColor: themeColor }], margin: [0, 16, 0, 20] },

        {
          columns: [
            {
              width: '*',
              fillColor: PDF_COLORS.panelBg,
              margin: [10, 8, 10, 8],
              stack: [
                { text: 'BILLED TO', fontSize: 7, bold: true, color: PDF_COLORS.lightText },
                { text: `${invoice.patient?.firstName || ''} ${invoice.patient?.lastName || ''}`.trim(), bold: true, margin: [0, 4, 0, 0] },
                ...(invoice.patient?.phone ? [{ text: invoice.patient.phone, fontSize: 9 }] : []),
                ...(invoice.patient?.email ? [{ text: invoice.patient.email, fontSize: 9 }] : []),
              ],
            },
            {
              width: '*',
              fillColor: PDF_COLORS.panelBg,
              margin: [10, 8, 10, 8],
              stack: [
                { text: 'PAYMENT INFO', fontSize: 7, bold: true, color: PDF_COLORS.lightText },
                {
                  text: invoice.paymentMethod ? `Method: ${String(invoice.paymentMethod).replace('_', ' ')}` : 'Payment pending',
                  fontSize: 9,
                  margin: [0, 4, 0, 0],
                },
                ...(invoice.paidAt ? [{ text: `Paid: ${fmtDate(invoice.paidAt)}`, fontSize: 9 }] : []),
                ...((invoice as any).paymentTransactionId ? [{ text: `Txn: ${(invoice as any).paymentTransactionId}`, fontSize: 8, color: PDF_COLORS.mutedText }] : []),
              ],
            },
          ],
          columnGap: 16,
          margin: [0, 0, 0, 20],
        },

        {
          table: {
            headerRows: 1,
            widths: ['*', 50, 80, 80],
            body: [
              [
                { text: 'Description', fillColor: themeColor, color: '#ffffff', bold: true, fontSize: 9 },
                { text: 'Qty', fillColor: themeColor, color: '#ffffff', bold: true, fontSize: 9, alignment: 'center' },
                { text: 'Unit Price', fillColor: themeColor, color: '#ffffff', bold: true, fontSize: 9, alignment: 'right' },
                { text: 'Total', fillColor: themeColor, color: '#ffffff', bold: true, fontSize: 9, alignment: 'right' },
              ],
              ...itemRows,
            ],
          },
          layout: {
            hLineWidth: () => 0.5,
            vLineWidth: () => 0,
            hLineColor: () => PDF_COLORS.border,
          },
          margin: [0, 0, 0, 16],
        },

        {
          table: { widths: [140, 100], body: totalsRows },
          layout: 'noBorders',
          alignment: 'right',
          margin: [283, 0, 0, 0],
        },

        ...(invoice.notes
          ? [{
              text: [{ text: 'Notes: ', bold: true, color: PDF_COLORS.darkText }, invoice.notes],
              fillColor: PDF_COLORS.panelBg,
              fontSize: 9,
              color: PDF_COLORS.mutedText,
              margin: [10, 28, 10, 8] as [number, number, number, number],
            }]
          : []),

        {
          text: footerParts.join('  •  '),
          fontSize: 8,
          color: PDF_COLORS.lightText,
          alignment: 'center',
          margin: [0, 40, 0, 0],
        },
      ],
    };
    return renderPdfDoc(docDefinition);
  }

  buildInvoiceHtml(invoice: Invoice, clinic: Clinic): string {
    const fmtDate = (d: any) =>
      d
        ? new Date(d).toLocaleDateString('en', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })
        : '—';
    const fmtNPR = (n: number | string) =>
      `NPR ${Number(n).toLocaleString('en')}`;

    const rows = (invoice.items || [])
      .map(
        (item: any) => `
      <tr>
        <td style="padding:10px 8px;border-bottom:1px solid #e5e7eb">${item.description}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #e5e7eb;text-align:center">${item.quantity}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #e5e7eb;text-align:right">${fmtNPR(item.unitPrice)}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #e5e7eb;text-align:right;font-weight:600">${fmtNPR(item.total)}</td>
      </tr>`,
      )
      .join('');

    const tpl = clinic.billingTemplate || {};
    const themeColor    = tpl.themeColor || '#027cc6';
    // Default OFF (only show if explicitly enabled in template)
    const showLogo      = tpl.showLogo    === true;
    const showVat       = tpl.showVatNumber       === true;
    const showReg       = tpl.showRegistrationNumber === true;
    const showLicense   = tpl.showLicenseNumber   === true;

    const API_BASE = process.env.API_BASE_URL || 'http://localhost:4000';
    const logoHtml = showLogo && clinic?.logo
      ? `<img src="${clinic.logo.startsWith('http') ? clinic.logo : `${API_BASE}${clinic.logo}`}" alt="logo" style="max-height:56px;max-width:160px;object-fit:contain;display:block;margin-bottom:6px" />`
      : '';

    const clinicMeta = [
      clinic?.address,
      clinic?.phone,
      clinic?.email,
      showLicense && clinic?.licenseNumber      ? `License: ${clinic.licenseNumber}`             : null,
      showReg     && clinic?.registrationNumber  ? `Reg No: ${clinic.registrationNumber}`          : null,
      showVat     && clinic?.vatNumber           ? `VAT No: ${clinic.vatNumber}`                   : null,
    ]
      .filter(Boolean)
      .join('<br>');

    const headerNote = tpl.headerNote ? `<div style="font-size:11px;color:#6b7280;margin-top:4px;font-style:italic">${tpl.headerNote}</div>` : '';
    const footerNote = tpl.footerNote ? `<p style="margin-top:20px;text-align:center;font-size:11px;color:#9ca3af;font-style:italic">${tpl.footerNote}</p>` : '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Invoice ${invoice.invoiceNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #1f2937; background: #fff; }
  .page { max-width: 800px; margin: 0 auto; padding: 36px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 36px; border-bottom: 3px solid ${themeColor}; padding-bottom: 20px; }
  .brand { font-size: 26px; font-weight: 800; color: ${themeColor}; }
  .clinic-info { text-align: right; font-size: 12px; color: #6b7280; line-height: 1.7; }
  .clinic-name { font-size: 15px; font-weight: 700; color: #1f2937; }
  .invoice-title { font-size: 22px; font-weight: 700; color: #1f2937; margin-bottom: 4px; }
  .invoice-meta { color: #6b7280; font-size: 12px; line-height: 1.8; }
  .parties { display: flex; gap: 24px; margin-bottom: 28px; }
  .party { flex: 1; padding: 14px 16px; background: #f9fafb; border-radius: 8px; border-left: 3px solid ${themeColor}; }
  .party h4 { font-size: 9px; text-transform: uppercase; letter-spacing: .1em; color: #9ca3af; margin-bottom: 6px; }
  .party p { font-size: 13px; color: #1f2937; line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  thead tr { background: ${themeColor}; color: #fff; }
  thead th { padding: 11px 8px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .06em; }
  thead th:nth-child(2) { text-align: center; }
  thead th:nth-child(3), thead th:nth-child(4) { text-align: right; }
  .totals { margin-left: auto; width: 280px; }
  .totals table td { padding: 6px 8px; font-size: 13px; }
  .totals .grand { background: ${themeColor}; color: #fff; font-size: 15px; font-weight: 700; border-radius: 6px; }
  .status-badge { display: inline-block; padding: 4px 12px; border-radius: 99px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .06em; }
  .paid   { background: #d1fae5; color: #065f46; }
  .unpaid { background: #fee2e2; color: #991b1b; }
  .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  .reg-info { display: flex; gap: 16px; flex-wrap: wrap; font-size: 11px; color: #6b7280; margin-top: 6px; }
  .reg-info span { padding: 2px 8px; background: #f3f4f6; border-radius: 4px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div>
      // <div class="brand">🦷 DentalOS</div>
      <div style="margin-top:10px">
        <div class="invoice-title">INVOICE</div>
        <div class="invoice-meta">
          <div><strong>#${invoice.invoiceNumber}</strong></div>
          <div>Issued: ${fmtDate(invoice.createdAt)}</div>
          ${invoice.dueDate ? `<div>Due: ${fmtDate(invoice.dueDate)}</div>` : ''}
          <div style="margin-top:6px">
            <span class="status-badge ${invoice.status === 'paid' ? 'paid' : 'unpaid'}">${invoice.status.replace('_', ' ')}</span>
          </div>
        </div>
      </div>
    </div>
    <div class="clinic-info">
      ${logoHtml}
      <div class="clinic-name">${clinic?.name || 'Dental Clinic'}</div>
      <div style="margin-top:4px">${clinicMeta}</div>
    </div>
  </div>

  <div class="parties">
    <div class="party">
      <h4>Billed To</h4>
      <p>
        <strong>${invoice.patient?.firstName || ''} ${invoice.patient?.lastName || ''}</strong><br>
        ${invoice.patient?.phone ? invoice.patient.phone + '<br>' : ''}
        ${invoice.patient?.email || ''}
      </p>
    </div>
    <div class="party">
      <h4>Payment Info</h4>
      <p>
        ${invoice.paymentMethod ? `Method: ${String(invoice.paymentMethod).replace('_', ' ')}` : 'Payment pending'}<br>
        ${invoice.paidAt ? `Paid: ${fmtDate(invoice.paidAt)}` : ''}
        ${(invoice as any).paymentTransactionId ? `<br>Txn: ${(invoice as any).paymentTransactionId}` : ''}
      </p>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th style="text-align:center">Qty</th>
        <th style="text-align:right">Unit Price</th>
        <th style="text-align:right">Total</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">
    <table>
      <tr><td>Subtotal</td><td style="text-align:right">${fmtNPR(invoice.subtotal)}</td></tr>
      ${Number(invoice.taxAmount) > 0 ? `<tr><td>VAT (${invoice.taxPercent}%)</td><td style="text-align:right">${fmtNPR(invoice.taxAmount)}</td></tr>` : ''}
      ${Number(invoice.discountAmount) > 0 ? `<tr><td>Discount</td><td style="text-align:right">- ${fmtNPR(invoice.discountAmount)}</td></tr>` : ''}
      <tr class="grand"><td>Total</td><td style="text-align:right">${fmtNPR(invoice.total)}</td></tr>
      ${Number(invoice.paidAmount) > 0 ? `<tr><td style="color:#6b7280">Paid</td><td style="text-align:right;color:#6b7280">${fmtNPR(invoice.paidAmount)}</td></tr>` : ''}
      ${Number(invoice.dueAmount) > 0 ? `<tr><td style="color:#dc2626;font-weight:700">Balance Due</td><td style="text-align:right;color:#dc2626;font-weight:700">${fmtNPR(invoice.dueAmount)}</td></tr>` : ''}
    </table>
  </div>

  ${invoice.notes ? `<div style="margin-top:28px;padding:14px 16px;background:#f9fafb;border-radius:8px;border-left:3px solid #d1d5db;font-size:12px;color:#6b7280"><strong style="color:#374151">Notes:</strong> ${invoice.notes}</div>` : ''}

  ${footerNote}
  <div class="footer">
    Generated by DentalOS &bull; ${new Date().getFullYear()}
    ${showVat && clinic?.vatNumber           ? `&bull; VAT: ${clinic.vatNumber}`             : ''}
    ${showReg && clinic?.registrationNumber  ? `&bull; Reg: ${clinic.registrationNumber}`    : ''}
  </div>
</div>
</body>
</html>`;
  }
}