import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenDiff1783827206937 implements MigrationInterface {
    name = 'AutoGenDiff1783827206937'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_sync_devices_clinicId"`);
        await queryRunner.query(`CREATE TABLE "recalls" ("id" varchar PRIMARY KEY NOT NULL, "clinicId" varchar NOT NULL, "patientId" varchar NOT NULL, "createdByUserId" varchar, "dueDate" date NOT NULL, "reason" varchar, "recallType" varchar CHECK( "recallType" IN ('checkup','followup','medication_review','other') ) NOT NULL DEFAULT ('checkup'), "status" varchar CHECK( "status" IN ('pending','contacted','booked','cancelled') ) NOT NULL DEFAULT ('pending'), "notes" text, "appointmentId" varchar, "reminderSentAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb783585db7058971881aced0f" ON "recalls" ("clinicId", "patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_69f1e61cba19589d3e6e588caf" ON "recalls" ("clinicId", "status", "dueDate") `);
        await queryRunner.query(`CREATE TABLE "temporary_clinics" ("syncStatus" varchar(20) NOT NULL DEFAULT ('synced'), "id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "email" varchar, "phone" varchar, "address" varchar, "city" varchar, "logo" varchar, "website" varchar, "licenseNumber" varchar, "registrationNumber" varchar, "vatNumber" varchar, "plan" varchar CHECK( "plan" IN ('free','basic','pro','enterprise') ) NOT NULL DEFAULT ('free'), "workingHours" text, "settings" text, "billingTemplate" text DEFAULT ('{}'), "prescriptionTemplate" text DEFAULT ('{}'), "isActive" boolean NOT NULL DEFAULT (1), "trialEndsAt" datetime, "subscriptionEndsAt" datetime, "isPubliclyListed" boolean NOT NULL DEFAULT (0), "publicDescription" text, "coverImageUrl" varchar, "galleryImages" text, "categoryTags" text, "openingHours" text, "latitude" decimal(10,7), "longitude" decimal(10,7), "acceptsInsurance" boolean NOT NULL DEFAULT (0), "insuranceProviders" text, "languagesSpoken" text, "isEmergencyCapable" boolean NOT NULL DEFAULT (0), "isOpen24Hours" boolean NOT NULL DEFAULT (0), "rating" decimal(3,2), "reviewCount" integer NOT NULL DEFAULT (0), "cancellationWindowHours" integer NOT NULL DEFAULT (24), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "isLocalPlaceholder" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_1c4933755297e407da44d46031c" UNIQUE ("slug"))`);
        await queryRunner.query(`INSERT INTO "temporary_clinics"("syncStatus", "id", "name", "slug", "email", "phone", "address", "city", "logo", "website", "licenseNumber", "registrationNumber", "vatNumber", "plan", "workingHours", "settings", "billingTemplate", "prescriptionTemplate", "isActive", "trialEndsAt", "subscriptionEndsAt", "isPubliclyListed", "publicDescription", "coverImageUrl", "galleryImages", "categoryTags", "openingHours", "latitude", "longitude", "acceptsInsurance", "insuranceProviders", "languagesSpoken", "isEmergencyCapable", "isOpen24Hours", "rating", "reviewCount", "cancellationWindowHours", "createdAt", "updatedAt") SELECT "syncStatus", "id", "name", "slug", "email", "phone", "address", "city", "logo", "website", "licenseNumber", "registrationNumber", "vatNumber", "plan", "workingHours", "settings", "billingTemplate", "prescriptionTemplate", "isActive", "trialEndsAt", "subscriptionEndsAt", "isPubliclyListed", "publicDescription", "coverImageUrl", "galleryImages", "categoryTags", "openingHours", "latitude", "longitude", "acceptsInsurance", "insuranceProviders", "languagesSpoken", "isEmergencyCapable", "isOpen24Hours", "rating", "reviewCount", "cancellationWindowHours", "createdAt", "updatedAt" FROM "clinics"`);
        await queryRunner.query(`DROP TABLE "clinics"`);
        await queryRunner.query(`ALTER TABLE "temporary_clinics" RENAME TO "clinics"`);
        await queryRunner.query(`DROP INDEX "IDX_bb783585db7058971881aced0f"`);
        await queryRunner.query(`DROP INDEX "IDX_69f1e61cba19589d3e6e588caf"`);
        await queryRunner.query(`CREATE TABLE "temporary_recalls" ("id" varchar PRIMARY KEY NOT NULL, "clinicId" varchar NOT NULL, "patientId" varchar NOT NULL, "createdByUserId" varchar, "dueDate" date NOT NULL, "reason" varchar, "recallType" varchar CHECK( "recallType" IN ('checkup','followup','medication_review','other') ) NOT NULL DEFAULT ('checkup'), "status" varchar CHECK( "status" IN ('pending','contacted','booked','cancelled') ) NOT NULL DEFAULT ('pending'), "notes" text, "appointmentId" varchar, "reminderSentAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_a9e11f8351b23b8fcf47cce2cee" FOREIGN KEY ("patientId") REFERENCES "patients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_75c871c01751e6964d9e2d4914a" FOREIGN KEY ("createdByUserId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_2759a8526b7a5d9d20f145bfadf" FOREIGN KEY ("appointmentId") REFERENCES "appointments" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_recalls"("id", "clinicId", "patientId", "createdByUserId", "dueDate", "reason", "recallType", "status", "notes", "appointmentId", "reminderSentAt", "createdAt", "updatedAt") SELECT "id", "clinicId", "patientId", "createdByUserId", "dueDate", "reason", "recallType", "status", "notes", "appointmentId", "reminderSentAt", "createdAt", "updatedAt" FROM "recalls"`);
        await queryRunner.query(`DROP TABLE "recalls"`);
        await queryRunner.query(`ALTER TABLE "temporary_recalls" RENAME TO "recalls"`);
        await queryRunner.query(`CREATE INDEX "IDX_bb783585db7058971881aced0f" ON "recalls" ("clinicId", "patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_69f1e61cba19589d3e6e588caf" ON "recalls" ("clinicId", "status", "dueDate") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_69f1e61cba19589d3e6e588caf"`);
        await queryRunner.query(`DROP INDEX "IDX_bb783585db7058971881aced0f"`);
        await queryRunner.query(`ALTER TABLE "recalls" RENAME TO "temporary_recalls"`);
        await queryRunner.query(`CREATE TABLE "recalls" ("id" varchar PRIMARY KEY NOT NULL, "clinicId" varchar NOT NULL, "patientId" varchar NOT NULL, "createdByUserId" varchar, "dueDate" date NOT NULL, "reason" varchar, "recallType" varchar CHECK( "recallType" IN ('checkup','followup','medication_review','other') ) NOT NULL DEFAULT ('checkup'), "status" varchar CHECK( "status" IN ('pending','contacted','booked','cancelled') ) NOT NULL DEFAULT ('pending'), "notes" text, "appointmentId" varchar, "reminderSentAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "recalls"("id", "clinicId", "patientId", "createdByUserId", "dueDate", "reason", "recallType", "status", "notes", "appointmentId", "reminderSentAt", "createdAt", "updatedAt") SELECT "id", "clinicId", "patientId", "createdByUserId", "dueDate", "reason", "recallType", "status", "notes", "appointmentId", "reminderSentAt", "createdAt", "updatedAt" FROM "temporary_recalls"`);
        await queryRunner.query(`DROP TABLE "temporary_recalls"`);
        await queryRunner.query(`CREATE INDEX "IDX_69f1e61cba19589d3e6e588caf" ON "recalls" ("clinicId", "status", "dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb783585db7058971881aced0f" ON "recalls" ("clinicId", "patientId") `);
        await queryRunner.query(`ALTER TABLE "clinics" RENAME TO "temporary_clinics"`);
        await queryRunner.query(`CREATE TABLE "clinics" ("syncStatus" varchar(20) NOT NULL DEFAULT ('synced'), "id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "email" varchar, "phone" varchar, "address" varchar, "city" varchar, "logo" varchar, "website" varchar, "licenseNumber" varchar, "registrationNumber" varchar, "vatNumber" varchar, "plan" varchar CHECK( "plan" IN ('free','basic','pro','enterprise') ) NOT NULL DEFAULT ('free'), "workingHours" text, "settings" text, "billingTemplate" text DEFAULT ('{}'), "prescriptionTemplate" text DEFAULT ('{}'), "isActive" boolean NOT NULL DEFAULT (1), "trialEndsAt" datetime, "subscriptionEndsAt" datetime, "isPubliclyListed" boolean NOT NULL DEFAULT (0), "publicDescription" text, "coverImageUrl" varchar, "galleryImages" text, "categoryTags" text, "openingHours" text, "latitude" decimal(10,7), "longitude" decimal(10,7), "acceptsInsurance" boolean NOT NULL DEFAULT (0), "insuranceProviders" text, "languagesSpoken" text, "isEmergencyCapable" boolean NOT NULL DEFAULT (0), "isOpen24Hours" boolean NOT NULL DEFAULT (0), "rating" decimal(3,2), "reviewCount" integer NOT NULL DEFAULT (0), "cancellationWindowHours" integer NOT NULL DEFAULT (24), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_1c4933755297e407da44d46031c" UNIQUE ("slug"))`);
        await queryRunner.query(`INSERT INTO "clinics"("syncStatus", "id", "name", "slug", "email", "phone", "address", "city", "logo", "website", "licenseNumber", "registrationNumber", "vatNumber", "plan", "workingHours", "settings", "billingTemplate", "prescriptionTemplate", "isActive", "trialEndsAt", "subscriptionEndsAt", "isPubliclyListed", "publicDescription", "coverImageUrl", "galleryImages", "categoryTags", "openingHours", "latitude", "longitude", "acceptsInsurance", "insuranceProviders", "languagesSpoken", "isEmergencyCapable", "isOpen24Hours", "rating", "reviewCount", "cancellationWindowHours", "createdAt", "updatedAt") SELECT "syncStatus", "id", "name", "slug", "email", "phone", "address", "city", "logo", "website", "licenseNumber", "registrationNumber", "vatNumber", "plan", "workingHours", "settings", "billingTemplate", "prescriptionTemplate", "isActive", "trialEndsAt", "subscriptionEndsAt", "isPubliclyListed", "publicDescription", "coverImageUrl", "galleryImages", "categoryTags", "openingHours", "latitude", "longitude", "acceptsInsurance", "insuranceProviders", "languagesSpoken", "isEmergencyCapable", "isOpen24Hours", "rating", "reviewCount", "cancellationWindowHours", "createdAt", "updatedAt" FROM "temporary_clinics"`);
        await queryRunner.query(`DROP TABLE "temporary_clinics"`);
        await queryRunner.query(`DROP INDEX "IDX_69f1e61cba19589d3e6e588caf"`);
        await queryRunner.query(`DROP INDEX "IDX_bb783585db7058971881aced0f"`);
        await queryRunner.query(`DROP TABLE "recalls"`);
        await queryRunner.query(`CREATE INDEX "IDX_sync_devices_clinicId" ON "sync_devices" ("clinicId") `);
    }

}